#if: branch = dev
language: node_js
node_js:
  - 12

cache:
  npm: true
  directories:
    - ./node_modules

before_script:
  - npm install

before_install:
  - chmod +x travis_merge_script.sh

after_success:
  - ./travis_merge_script.sh

script:
  - npm run build
  - npm run test

deploy:
  - provider: script
    skip_cleanup: true
    script:
      echo "I am true"
    on:
      branch: master

