#if: branch = dev
language: node_js
node_js:
  - 12

cache:
  npm: true
  directories:
    - ./node_modules

before_script:
  - npm install

before_install:
  - chmod +x travis_merge_script.sh

after_success:
  - ./travis_merge_script.sh

#script:
#  - npm run build

deploy:
  - provider: script
    skip_cleanup: true
    script:
      npm run build ;
      echo "I am true, Deploy here..."
    #deploy to AWS, Firebase, Heroku
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script:
      npm run test:unit
    on:
      branch: dev

